#!/usr/bin/env python2.5
# -*- coding: utf-8 -*-
try:
  from fremantle import pysafe
except ImportError:
  # assumindo que estamos num desktop!
  from desktop import pysafe

if __name__ == "__main__":
  pysafe()
